[debian13][x64] add min and nfs variants

diff --git a/steps/setup/debian/run_orchestrator.yaml b/steps/setup/debian/run_orchestrator.yaml
--- a/steps/setup/debian/run_orchestrator.yaml
+++ b/steps/setup/debian/run_orchestrator.yaml
@@ -3,6 +3,7 @@
 - hiera_path: "/tmp/hiera"
 - puppet_local_path: $${kameleon_data_dir}/setup/puppet
 - hiera_local_path: $${kameleon_data_dir}/setup/hiera
+- modules_path: "/etc/puppet/code/modules"
 - version_file: modules/env/files/version
 - release_file: modules/env/files/min/image_versioning/release
 - kameleon_repo_name : "default"
@@ -30,14 +31,30 @@
   - exec_in: echo "$${g5k_version}" > $${puppet_build_path}/$${version_file}
 
 - run_puppet:
-  - exec_in: |
-      set +e
-      if [ -z "$${g5k_variant}" ]; then
-        VARIANT=std
-      else
-        VARIANT=$${g5k_variant}
-      fi
-      puppet apply --detailed-exitcodes -d --modulepath=$${puppet_build_path}/modules:/etc/puppet/code/modules $${puppet_build_path}/manifests/$VARIANT.pp | tee /tmp/puppet_exec.log
-      ret=$?
-      echo $ret
-      if [ $ret -eq 2 -o $ret -eq 0 ] ; then true ; else false ; fi # Set exit code to 0
+  - test:
+    - exec_in: test "$${release}" == "trixie"
+    - exec_in: |
+        source /root/.profile
+        set +e
+        if [ -z "$${g5k_variant}" ]; then
+          VARIANT=std
+        else
+          VARIANT=$${g5k_variant}
+        fi
+        /opt/puppetlabs/bin/puppet apply --detailed-exitcodes -d --modulepath=$${puppet_build_path}/modules:/etc/puppetlabs/code/environments/production/modules $${puppet_build_path}/manifests/$VARIANT.pp | tee /tmp/puppet_exec.log
+        ret=$?
+        echo $ret
+        if [ $ret -eq 2 -o $ret -eq 0 ] ; then true ; else false ; fi # Set exit code to 0
+  - test:
+    - exec_in: test "$${release}" != "trixie"
+    - exec_in: |
+        set +e
+        if [ -z "$${g5k_variant}" ]; then
+          VARIANT=std
+        else
+          VARIANT=$${g5k_variant}
+        fi
+        puppet apply --detailed-exitcodes -d --modulepath=$${puppet_build_path}/modules:$${modules_path} $${puppet_build_path}/manifests/$VARIANT.pp | tee /tmp/puppet_exec.log
+        ret=$?
+        echo $ret
+        if [ $ret -eq 2 -o $ret -eq 0 ] ; then true ; else false ; fi # Set exit code to 0
